apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-backend
  template:
    metadata:
      labels:
        app: student-backend
    spec:
      containers:
        - name: student-backend
          image: vinaydaripelly/student-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URL
              value: "mongodb+srv://daripellyvinay_db_user:TjPsUQZWyCFyWToo@cluster0.vqtpnab.mongodb.net/?retryWrites=true&w=majority"